version: '3.9'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app
    restart: always
    ports:
      - 8000:8000
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
